version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/workspace
    working_dir: /workspace
    ports:
      - "8000:8000"
    environment:
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_DEBUG: "1"
      DJANGO_SECRET_KEY: "dev-please-change"
    command: bash -lc "sleep infinity"
