# Generated by Django 5.0.14 on 2025-09-30 01:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_grouprequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gameparticipation',
            name='rebuy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Rebuy'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='game',
            name='location',
            field=models.CharField(blank=True, max_length=180, verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(blank=True, max_length=140, verbose_name='Nome da partida'),
        ),
        migrations.AlterField(
            model_name='gameparticipation',
            name='final_balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stack final'),
        ),
        migrations.AlterField(
            model_name='gameparticipation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_participations', to=settings.AUTH_USER_MODEL, verbose_name='Jogador'),
        ),
    ]
